# Generated by Django 5.1.3 on 2024-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
    ]
