# Generated by Django 5.1.3 on 2024-12-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantina_app', '0002_customuser_is_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_logged',
        ),
    ]
